In [1]:
import numpy as np
import math

In [2]:
A = np.array([
    [1, 0],
    [1, 1],
    [0, 1],
])

In [3]:
A

array([[1, 0],
       [1, 1],
       [0, 1]])

In [4]:
v1 = np.transpose(A)[0]

In [5]:
v2 = np.transpose(A)[1]

In [6]:
v1

array([1, 1, 0])

In [7]:
v2

array([0, 1, 1])

In [8]:
u1 = v1

In [9]:
u1_dlugosc = math.sqrt(np.dot(u1, u1))

In [10]:
u1_dlugosc

1.4142135623730951

In [11]:
e1 = u1 / u1_dlugosc

In [12]:
e1

array([0.70710678, 0.70710678, 0.        ])

In [13]:
u2 = v2 - np.dot(np.dot(v2, u1) / np.dot(u1, u1), u1)

In [14]:
u2

array([-0.5,  0.5,  1. ])

In [15]:
u2_dlugosc = math.sqrt(np.dot(u2, u2))

In [16]:
u2_dlugosc

1.224744871391589

In [17]:
e2 = u2 / u2_dlugosc

In [18]:
e2

array([-0.40824829,  0.40824829,  0.81649658])

In [19]:
Q = np.zeros((len(A.T), len(A)))
Q[0] = e1
Q[1] = e2
Q = np.transpose(Q)

In [20]:
Q

array([[ 0.70710678, -0.40824829],
       [ 0.70710678,  0.40824829],
       [ 0.        ,  0.81649658]])

In [21]:
R = Q.T @ A

In [22]:
R

array([[1.41421356, 0.70710678],
       [0.        , 1.22474487]])

In [23]:
QR = Q @ R

In [24]:
np.round(np.fabs(QR))

array([[1., 0.],
       [1., 1.],
       [0., 1.]])

In [25]:
round(QR[0][1], 0)

-0.0